# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c901b428330f09cb394acf0985395a8fc3b6561907657b863bed2fbdce3ec1f5333bd689c04706cf062f228a4cb6580c38ad014e1508d9c0a503b72af5b1ea9

test:
  secret_key_base: e7c1dda6308bf8cce3792ace0ae92f0149f4c9e7df5fa53cf590b66629f53dd6e6272bba57fe79d534ea85d582d67ea3aa5ea039e0ec6ef2640827fe00cd2cfa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
